# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDefaultSuite():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_realTest1(self):
    # Test name: RealTest1
    # Step # | name | target | value
    # 1 | open | https://www.livechat.com/typing-speed-test/#/ | 
    self.driver.get("https://www.livechat.com/typing-speed-test/#/")
    # 2 | setWindowSize | 1075x816 | 
    self.driver.set_window_size(1075, 816)
    # 3 | mouseOver | linkText=Marketplace | 
    element = self.driver.find_element(By.LINK_TEXT, "Marketplace")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 4 | click | linkText=Product | 
    self.driver.find_element(By.LINK_TEXT, "Product").click()
    # 5 | click | linkText=Benefits | 
    self.driver.find_element(By.LINK_TEXT, "Benefits").click()
    # 6 | click | linkText=Use Cases | 
    self.driver.find_element(By.LINK_TEXT, "Use Cases").click()
    # 7 | mouseOver | linkText=Pricing | 
    element = self.driver.find_element(By.LINK_TEXT, "Pricing")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 8 | click | css=form:nth-child(3) .u-mr-xs | 
    self.driver.find_element(By.CSS_SELECTOR, "form:nth-child(3) .u-mr-xs").click()
    # 9 | mouseOver | css=form:nth-child(3) .c-btn | 
    element = self.driver.find_element(By.CSS_SELECTOR, "form:nth-child(3) .c-btn")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 10 | type | css=form:nth-child(3) .u-mr-xs | tEST
    self.driver.find_element(By.CSS_SELECTOR, "form:nth-child(3) .u-mr-xs").send_keys("tEST")
  
testSuite = TestDefaultSuite()

testSuite.setup_method(None)

testSuite.test_realTest1()